### ISSUE TITLE
push-docker-webapp takes too long

### ISSUE THREAD

**Issue by dononitram** [Arquisoft/wiq_es05b#112]
When deploying through github actions, push-docker-webapp job takes way too long for my mental sanity.

- A self-hosted runner would be ideal to fix this issue

**Comment by dononitram** [comment]
Well... it was fun trying

f498f8590b66c004b52f729ff8a36b2c173f2f86
d43283b2d2d1897cf65cedcd7c3773b46cd1e49a
bf0990cfc794fc941afa3765d8f67c5b43ef1259
92f9cc57d683294959752002c9a267fa54288273

![image](https://github.com/Arquisoft/wiq_es05b/assets/92989546/25321b96-e190-4a62-b400-3d679335af6e)
![image](https://github.com/Arquisoft/wiq_es05b/assets/92989546/0053c1cf-3059-4574-aa68-a5606b636dc3)

**Comment by dononitram** [comment]
In the bygone days of yore, a valiant soul endeavored to harness the ethereal powers of the GitHub Actions runner, a quest most noble and fraught with peril. This brave artisan, armed with naught but fervor and the scrolls of documentation, didst set forth to conjure the automation spirits within their own dominion. Alas, the capricious fates were not kind, and the endeavor met with a calamitous fate. The arcane machinations, complex beyond mortal ken, didst rebel against their master, leading to a series of misfortunes most dire. In the end, the gallant attempt lay in ruins, a testament to the hubris of man's reach exceeding his grasp. Yet, from the ashes of this woeful tale, wisdom was gleaned, and the echoes of the past shall guide future endeavors to glory. So let it be written, so let it be remembered – the saga of the GitHub Actions runner, a poetic odyssey of ambition and learning.

**Comment by algarfer** [comment]
> In the bygone days of yore, a valiant soul endeavored to harness the ethereal powers of the GitHub Actions runner, a quest most noble and fraught with peril. This brave artisan, armed with naught but fervor and the scrolls of documentation, didst set forth to conjure the automation spirits within their own dominion. Alas, the capricious fates were not kind, and the endeavor met with a calamitous fate. The arcane machinations, complex beyond mortal ken, didst rebel against their master, leading to a series of misfortunes most dire. In the end, the gallant attempt lay in ruins, a testament to the hubris of man's reach exceeding his grasp. Yet, from the ashes of this woeful tale, wisdom was gleaned, and the echoes of the past shall guide future endeavors to glory. So let it be written, so let it be remembered – the saga of the GitHub Actions runner, a poetic odyssey of ambition and learning.

Oh, the saga of the GitHub Actions runner, a tale as old as the code itself! Here lies the chronicle of a valiant soul, a coder of unwavering determination, who dared to delve into the arcane depths of automation. With the scrolls of documentation as their only guide, they embarked on a quest to master the ethereal powers of the GitHub Actions runner. Their heart ablaze with fervor, they sought to bend the automation spirits to their will, to create a dominion where code would flow like a river, unimpeded and ever-forward.

But, as the annals of history have shown us time and again, the path of innovation is strewn with trials and tribulations. The capricious fates, ever so whimsical, looked not favorably upon our hero's endeavor. The arcane machinations, those complex constructs that weave the fabric of automation, turned rogue. They rebelled against their creator, unleashing a series of misfortunes most dire, a cascade of calamities that brought the noble attempt to its knees.

Yet, in the smoldering ruins of this ambitious enterprise, the embers of wisdom glowed hot. From the ashes rose not just the specter of defeat, but the seeds of understanding, hard-earned and precious. The echoes of this past misadventure now resonate through the corridors of time, a guiding light for those who dare to walk the same path.

Let this be a testament to the indomitable spirit of exploration, to the courage to reach beyond the grasp, to the insatiable quest for knowledge. For even in failure, there is a victory to be claimed – the acquisition of knowledge, the sharpening of skills, the fortification of resolve. So let it be written, so let it be done, that the saga of the GitHub Actions runner shall be a beacon of ambition and a symphony of learning, forevermore.

**Comment by algarfer** [comment]
https://stackoverflow.com/questions/74795993/unable-to-pull-public-image-from-github-container-registry-ghcr

**Comment by dononitram** [comment]
60e6b3209926fbe41ec341c533820ec3c57260c4 🥳🥳
