### ISSUE TITLE
Fix e2e tests

### ISSUE THREAD

**Issue by dononitram** [Arquisoft/wiq_es05b#139]
e2e fails since there is a syntax error in the chrome executable.

![image](https://github.com/Arquisoft/wiq_es05b/assets/92989546/451b22f8-8dbd-4fab-a688-2965b2e2c89d)

Also the test fails because the browser is undefined and can not be closed.

![image](https://github.com/Arquisoft/wiq_es05b/assets/92989546/d87e9f3c-f819-4a8e-9b00-8726db016e15)

**Comment by augustocristian** [comment]
![image](https://github.com/Arquisoft/wiq_es05b/assets/49859508/ce56ec58-ccc9-4f2d-bc2d-93c16a2516b6)
