### ISSUE TITLE
Include several self-hosted github action runners

### ISSUE THREAD

**Issue by dononitram** [Arquisoft/wiq_es05b#171]
Currently Conocer y Triunfar is being deployed thanks to ubuntu-latest machines hosted by github and a single self-hosted machine which is actually the same one where the project runs publicly.

More self-hosted machines would decrease costs in time and monthly hour limit.

Since the runners can't run different tasks on parallel, almost as many processes as microservices deployed would be needed.

**Comment by algarfer** [comment]
Done
