### ISSUE TITLE
Include alternatives in ADRs

### ISSUE THREAD

**Issue by algarfer** [Arquisoft/wiq_es05b#36]

**Comment by DonatoMartin** [comment]
Everything updated except for:
https://github.com/Arquisoft/wiq_es05b/wiki/ADR-05-%E2%80%90-MongoDB
https://github.com/Arquisoft/wiq_es05b/wiki/ADR-06-%E2%80%90-ExpressJS

@uo289321 (Luna) you can do the rest 😼

![CatTypingGIF](https://github.com/Arquisoft/wiq_es05b/assets/92989546/91f641c4-2fa3-4a0d-b23d-7ad6108737bd)
