### ISSUE TITLE
Make signup / login work properly

### ISSUE THREAD

**Issue by algarfer** [Arquisoft/wiq_es05b#64]
The login system must:
- [x] Be able to generate a unique token to identify registered users for protected endpoints
- [x] Make the webapp able to storage the user data in the localStorage and also be able to recover it.

The signup system must:
- [x] The signup should check the user is not blank or empty
- [x] The signup should check the password format (lower case, upper case, number and special character should be present and be 8 characters long at least)
- [x] The signup should also return a login ticket to prevent the user to login after creating an account
- [x] It shouldn't be users with the same username

**Comment by dononitram** [comment]
Login enhanced
