### ISSUE TITLE
Self Report 2 - Luna Valdés (UO289321)

### ISSUE THREAD

**Issue by uo289321** [Arquisoft/wiq_es05b#70]
# Work done during the second deliverable
![image](https://github.com/Arquisoft/wiq_es05b/assets/144900498/33eda29a-0af5-471e-be5e-334b6a1b328b)

## Documentation
 - #29
 - #36 

## Prototypes
 - #48

## App development
- #68 
- #63

**Comment by dononitram** [comment]
# ☣️Copying other team members is a very dishonorable practice!!! ☣️

I really hope you reconsider your future choices.

![PlinkCatGIF](https://github.com/Arquisoft/wiq_es05b/assets/92989546/e57cc57a-f4ce-4fe5-83cc-dd1b8dc33e63)

# 😡😡😡😡
