### ISSUE TITLE
Migrate docker release action from amd64 to arm64

### ISSUE THREAD

**Issue by algarfer** [Arquisoft/wiq_es05b#98]
The new docker images generated by the release workflow should be compatible with arm64 to work in the new VM

**Comment by augustocristian** [comment]
Check:  https://github.com/pglez82/asw2324_0/blob/master/.github/workflows/release.yml 
![image](https://github.com/Arquisoft/wiq_es05b/assets/49859508/bd74d7bc-a991-4919-a189-b1dd07d8bd89)
@algarfer @dononitram

**Comment by dononitram** [comment]
Ahora le echo un ojo

**Comment by algarfer** [comment]
Hola @augustocristian,

Ya había modificado ese workflow, solo que en la rama [develop](https://github.com/Arquisoft/wiq_es05b/tree/develop), en concreto en fd79202f48cb32203193cc6523fa5fea70d109cc.

Acabo de añadir ahora también la arquitectura amd64, ya que solo estaba la arm64 (f0d994649d6be3cda19e6389c581b39f1b0d2546)

**Comment by dononitram** [comment]
![microservice push example](https://github.com/Arquisoft/wiq_es05b/assets/92989546/576ff0ae-429a-4359-9fa7-28a2394376cd)
# Fixed
Migration completed, docker's buildx action was needed to compile for Arm64. Now the deploy is done on every push or pull request to master (might change later).
